"""Export coverage as an ATT&CK Navigator layer (v4.5 format) for the official Navigator UI."""
from __future__ import annotations

import json

from .coverage import CoverageResult
from .models import Catalog, CoverageStatus

COLORS = {CoverageStatus.DEFENDED: "#2e7d32", CoverageStatus.PAPER_ONLY: "#e65100",
          CoverageStatus.DETECTED_ONLY: "#1565c0", CoverageStatus.BLIND: "#b0b0b0"}
SCORES = {CoverageStatus.DEFENDED: 3, CoverageStatus.DETECTED_ONLY: 2,
          CoverageStatus.PAPER_ONLY: 1, CoverageStatus.BLIND: 0}


def to_layer(cat: Catalog, cov: CoverageResult, name: str = "VANTAGE coverage") -> dict:
    """ATT&CK Navigator layer (v4.5 format) coloured by coverage status."""
    techs = []
    for tid, st in sorted(cov.status.items()):
        t = cat.techniques[tid]
        for tactic in t.all_tactics:
            techs.append({
                "techniqueID": tid, "tactic": tactic, "score": SCORES[st], "color": COLORS[st],
                "comment": f"{st.value}; controls: {', '.join(sorted(cov.claimed[tid])) or '-'}; "
                           f"live rules: {len(cov.detected_by[tid])}",
                "enabled": True, "showSubtechniques": False,
            })
    return {
        "name": name, "domain": "enterprise-attack",
        "versions": {"attack": str(cat.meta.get("attack_version", "")).split(".")[0] or "19",
                     "navigator": "5.1.0", "layer": "4.5"},
        "description": "Generated by VANTAGE. SENSITIVE: a map of blind spots.",
        "techniques": techs,
        "legendItems": [{"label": s.value, "color": c} for s, c in COLORS.items()],
        "gradient": {"colors": ["#b0b0b0", "#2e7d32"], "minValue": 0, "maxValue": 3},
    }


def to_layer_json(cat: Catalog, cov: CoverageResult, name: str = "VANTAGE coverage") -> str:
    """``to_layer`` serialised as JSON."""
    return json.dumps(to_layer(cat, cov, name), indent=1)
