#!/usr/bin/env python
"""Print the declared minimum version of every dependency in every extra, pinned exactly.

    python scripts/min_constraints.py > /tmp/constraints-min.txt
    pip-audit -r /tmp/constraints-min.txt --no-deps --disable-pip

CI audits this list, so a pyproject.toml floor that still admits a release with a known
vulnerability fails the build. It is generated from pyproject.toml each time, so it never drifts.
Needs Python 3.11+ (tomllib).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parent.parent
_REQ = re.compile(r"^\s*([A-Za-z0-9._-]+)(\[[^\]]*\])?\s*(.*)$")


def floors(pyproject: Path = ROOT / "pyproject.toml") -> dict[str, str]:
    """name -> lowest allowed version (from a >= specifier) over core deps and every extra."""
    project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
    reqs = list(project.get("dependencies", []))
    for extra in project.get("optional-dependencies", {}).values():
        reqs += extra
    out: dict[str, str] = {}
    for r in reqs:
        m = _REQ.match(r.split(";")[0])
        if not m:
            raise SystemExit(f"cannot parse requirement {r!r}")
        name, spec = m.group(1).lower().replace("_", "-"), m.group(3)
        low = re.search(r">=\s*([0-9][^,\s]*)", spec)
        if not low:
            raise SystemExit(f"{r!r} has no >= floor to audit")
        out[name] = low.group(1)
    return out


def main() -> int:
    print("# generated by scripts/min_constraints.py from pyproject.toml")
    for name, ver in sorted(floors().items()):
        print(f"{name}=={ver}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
